//------------------------------------------------------------------------------
// <auto-generated>
//     Создано классом WriteCodeFragment MSBuild.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("SnakesLadders")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("SnakesLadders")]
[assembly: System.Reflection.AssemblyTitleAttribute("SnakesLadders")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
